### ISSUE TITLE
add replicaSet to MongoDB Service.

### ISSUE THREAD

**Issue by rodolv-commons** [gbv/coli-conc-server#22]
## MongoDB Replica Set in Docker Compose

Required for https://github.com/gbv/jskos-server/issues/228 

To enable change streams (`db.collection.watch()`), MongoDB must run as a replica set—even in a single-node setup. Proposed configuration of the mongo service is this  `docker-compose.yml`,  as follows:

```yaml
services:
  mongo:
    image: mongo:7
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - $DATA/mongo:/data/db
      - $HOME/backup:/backup
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
  
  mongo-setup-replica-set:
    image: mongo:7
    depends_on:
      - mongo
    volumes: 
      - $CONFIGS/mongo-initdb.d:/docker-entrypoint-initdb.d
    restart: "no"

networks:
  default:
    external: true
    name: mongo

```

In `./mongo-initdb.d`, include a script like:

```bash
#!/bin/bash
# mongo_setup.sh

# Wait for MongoDB to be ready
sleep 10

# Initiate the single-node replica set
mongosh --host mongo:27017 <<EOF
rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "mongo:27017" }] });
EOF
```

This setup ensures:

* **Replica set (`rs0`)** is initialized automatically at container start.
* **Change streams** work out of the box for real-time WebSocket endpoints.
* **Data persistence** via host-mounted volumes.
